name: Bike Rental Prediction CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements/test_requirements.txt
          
      - name: Model Training and Testing
        run: |
          python3 bikeshare_model/train_pipeline.py

  build-and-package:
    runs-on: ubuntu-latest

    needs: train-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements/test_requirements.txt

      - name: Build and Package
        run: |
          python3 -m pip install build
          python -m build

  dockerize:
    runs-on: ubuntu-latest

    needs: build-and-package

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: |
          COMMIT_SHA=$(git rev-parse --short=7 HEAD)
          docker build -t durgeshshisode1988/bikeshare_model_api:$COMMIT_SHA .

  push-to-dockerhub:
    runs-on: ubuntu-latest

    needs: dockerize

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push your-dockerhub-username/your-image-name:$COMMIT_SHA
